command:
  - uvicorn
  - main:app
  - --host=0.0.0.0
  - --port=8000

env:
  - name: FE_BAR_CHAIN_URL
    value: "https://fe-bar-chain-7474658263595816.aws.databricksapps.com"
  - name: GENIE_SPACE_ID
    value: "01f1c3da7f691ea7b087b1c6695bfdd3"
  - name: LLM_ENDPOINT
    value: "databricks-claude-opus-4-8"

resources:
  - name: sql-warehouse
    sql_warehouse:
      id: "0e54af629ab8456e"
      permission: CAN_USE
